### Ordinal encoding

In [8]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import OrdinalEncoder

### dataset load

In [9]:
df = pd.read_csv("/home/tanmoy/Desktop/Phitron/Machine Learning/Module7 - Encoding/Practice/titanic_data_updated.csv")
df.sample(5)

     PassengerId Survived  Pclass  ...     Fare Cabin  Embarked
524          525       no   third  ...   7.2292   NaN         C
782          783       no   first  ...  30.0000    D6         S
265          266       no  second  ...  10.5000   NaN         S
575          576       no   third  ...  14.5000   NaN         S
81            82      yes   third  ...   9.5000   NaN         S

[5 rows x 12 columns]

## Ordinal Encoding

In [11]:
encoded_pclass = OrdinalEncoder(categories=[['third', 'second', 'first']])
encoded_pclass.fit(df[["Pclass"]])
df["encoded_pclass"] = encoded_pclass.transform(df[["Pclass"]]).ravel()

In [15]:
df.sample(5)

     PassengerId Survived  Pclass  ... Cabin Embarked  encoded_pclass
183          184      yes  second  ...    F4        S             1.0
488          489       no   third  ...   NaN        S             0.0
1              2      yes   first  ...   C85        C             2.0
828          829      yes   third  ...   NaN        Q             0.0
619          620       no  second  ...   NaN        S             1.0

[5 rows x 13 columns]

## One Hot Encoding

In [17]:
from sklearn.preprocessing import OneHotEncoder
sex_one = OneHotEncoder(sparse_output=False).set_output(transform='pandas')
sex_one.fit(df[["Sex"]])
temp = sex_one.transform(df[["Sex"]])

df = pd.concat([df, temp], axis=1)
display(df.sample(5))

     PassengerId Survived  Pclass  ... encoded_pclass Sex_female  Sex_male
392          393       no   third  ...            0.0        0.0       1.0
354          355       no   third  ...            0.0        0.0       1.0
880          881      yes  second  ...            1.0        1.0       0.0
174          175       no   first  ...            2.0        0.0       1.0
792          793       no   third  ...            0.0        1.0       0.0

[5 rows x 15 columns]

In [ ]:
df["cabin_decki"] = df["Cabin"].astype(str).str[0]

In [21]:
df["cabin_decki"].value_counts()

cabin_decki
n    687
C     59
B     47
D     33
E     32
A     15
F     13
G      4
T      1
Name: count, dtype: int64

In [26]:
cabin_encode = OneHotEncoder(sparse_output=False,drop="first").set_output(transform='pandas')
cabin_encode.fit(df[["cabin_decki"]])
temp = cabin_encode.transform(df[["cabin_decki"]])
df = pd.concat([df, temp], axis=1)

In [27]:
df.sample(5)

     PassengerId Survived  Pclass  ... cabin_decki_G cabin_decki_T  cabin_decki_n
318          319      yes   first  ...           0.0           0.0            0.0
21            22      yes  second  ...           0.0           0.0            0.0
166          167      yes   first  ...           0.0           0.0            0.0
468          469       no   third  ...           0.0           0.0            1.0
473          474      yes  second  ...           0.0           0.0            0.0

[5 rows x 33 columns]