Registered email : tnmy468@gmail.com

In [1]:
import numpy as np
import pandas as pd

np.random.seed(24)

num_employees = 50  # you can increase this if needed

# Employee data
emp_ids = np.arange(101, 101 + num_employees)
emp_ages = np.random.randint(20, 55, num_employees)
emp_income = np.random.randint(35000, 95000, num_employees)

# Fixed set of roles (repetition allowed)
roles_list = [
    "HR Manager",
    "Software Developer",
    "Accountant",
    "Marketing Executive",
    "Sales Executive",
    "Backend Developer",
    "HR Executive",
    "Financial Analyst",
    "Digital Marketer",
    "Operations Manager"
]

emp_roles = np.random.choice(roles_list, num_employees)

# Create DataFrame
data = pd.DataFrame({
    "emp_id": emp_ids,
    "emp_age": emp_ages,
    "emp_salary": emp_income,
    "role": emp_roles
})

# Save dataset
data.to_csv("staff_data.csv", index=False)

# Q1

In [6]:
print(f"emp_ages : {emp_ages}")
print()
print(f"emp_income : {emp_income}")

print()
print("For emp_ages:")
print(f"data type: {emp_ages.dtype}")
print(f"number of dimension: ({emp_ages.ndim})")
print(f"shape: {emp_ages.shape}")
print(f"size: {emp_ages.size}")

print()
print("For emp_income")
print(f"data type: {emp_income.dtype}")
print(f"number of dimension: ({emp_income.ndim})")
print(f"shape: {emp_income.shape}")
print(f"size: {emp_income.size}")

emp_ages : [54 23 20 43 37 37 21 35 24 38 31 35 29 38 27 45 51 48 20 32 51 53 21 26
 53 37 26 21 45 30 20 47 53 53 23 24 21 30 27 25 39 20 47 41 22 52 42 54
 31 50]

emp_income : [51725 38495 35452 82295 72187 58915 76159 92864 76155 90494 68641 48079
 56879 83682 94722 91041 48899 68744 63187 74146 75641 47678 76760 78354
 60584 79898 59682 71888 51086 73700 82550 71447 76100 72269 73314 87428
 94427 84188 52013 63326 44396 59500 55523 58602 90794 41061 82331 73048
 59727 50398]

For emp_ages:
data type: int64
number of dimension: (1)
shape: (50,)
size: 50

For emp_income
data type: int64
number of dimension: (1)
shape: (50,)
size: 50

# Q2

In [9]:
print(f"maximum slary: {max(emp_income)}")
print(f"minimum slary: {min(emp_income)}")
print(f"avarage salary: {np.mean(emp_income)}")
print(f"avarage age: {np.mean(emp_ages)}")

maximum slary: 94722
minimum slary: 35452
avarage salary: 68409.48
avarage age: 35.44

# Q3

In [21]:
print(f"emp_ages: {emp_ages}")
print()
print(f"emp_income: {emp_income}")
print()

emp = np.where((emp_ages >= 25) & (emp_ages <= 40) & (emp_income > 50000))
emp = np.array(emp)

for i in range (len(emp)):
  print(f"employee: {emp_ids[emp[i]]}")

print()

print(f"number of {emp.size} employee satisfy this.")

emp_ages: [54 23 20 43 37 37 21 35 24 38 31 35 29 38 27 45 51 48 20 32 51 53 21 26
 53 37 26 21 45 30 20 47 53 53 23 24 21 30 27 25 39 20 47 41 22 52 42 54
 31 50]

emp_income: [51725 38495 35452 82295 72187 58915 76159 92864 76155 90494 68641 48079
 56879 83682 94722 91041 48899 68744 63187 74146 75641 47678 76760 78354
 60584 79898 59682 71888 51086 73700 82550 71447 76100 72269 73314 87428
 94427 84188 52013 63326 44396 59500 55523 58602 90794 41061 82331 73048
 59727 50398]

employee: [105 106 108 110 111 113 114 115 120 124 126 127 130 138 139 140 149]

number of 17 employee satisfy this.

# Q4

In [32]:
avarage_age = np.mean(emp_ages)

updated_age = emp_ages.copy()

for i in range (len(emp_ages)):
  if emp_ages[i] > avarage_age:
    updated_age[i] = updated_age[i] + 2
  else:
    updated_age[i] = updated_age[i] + 4

print(f"original age: {emp_ages}")
print()
print(f"updated age: {updated_age}")
print()
print(f"avarage age: {avarage_age}")

original age: [68 43 40 55 51 51 41 51 44 52 51 51 49 52 47 57 63 60 40 52 63 65 41 46
 65 51 46 41 57 50 40 59 65 65 43 44 41 50 47 45 51 40 59 53 42 64 54 66
 51 62]

updated age: [70 47 44 57 55 55 45 55 48 54 55 55 53 54 51 59 65 62 44 54 65 67 45 50
 67 55 50 45 59 54 44 61 67 67 47 48 45 54 51 49 55 44 61 55 46 66 56 68
 55 64]

avarage age: 51.68

# Q5

In [41]:
tech_role = np.where((emp_roles == 'Software Developer') | (emp_roles == 'Backend Developer'))

update_salary = emp_income.copy()

for i in range(len(tech_role)):
  update_salary[i] = update_salary[i] * 1.08

previous_sum = 0
for i in range (len(emp_income)):
  previous_sum = previous_sum + emp_income[i]

updated_sum = 0
for i in update_salary:
  updated_sum = updated_sum + i

print(f"previous sum: {previous_sum}")
print(f"updated sum: {updated_sum}")

print(f"overall increase in expense: {updated_sum - previous_sum}")

previous sum: 3420474
updated sum: 3424612
overall increase in expense: 4138

# Q6

In [42]:
df = pd.read_csv("staff_data.csv")

df.head(3)

   emp_id  emp_age  emp_salary                role
0     101       54       51725          HR Manager
1     102       23       38495          Accountant
2     103       20       35452  Operations Manager

In [43]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   emp_id      50 non-null     int64
 1   emp_age     50 non-null     int64
 2   emp_salary  50 non-null     int64
 3   role        50 non-null     object
dtypes: int64(3), object(1)
memory usage: 1.7+ KB

In [44]:
df.describe()

          emp_id    emp_age    emp_salary
count   50.00000  50.000000     50.000000
mean   125.50000  35.440000  68409.480000
std     14.57738  11.768446  15727.122334
min    101.00000  20.000000  35452.000000
25%    113.25000  24.250000  57309.750000
50%    125.50000  35.000000  72037.500000
75%    137.75000  46.500000  79512.000000
max    150.00000  54.000000  94722.000000

# Q7

In [48]:
age = df.loc[(df['emp_age'] >= 25) & (df['emp_age'] <= 40)]

data = df.sort_values('emp_id', ascending=True)

df.tail(3)

    emp_id  emp_age  emp_salary                 role
47     148       54       73048   Software Developer
48     149       31       59727     Digital Marketer
49     150       50       50398  Marketing Executive

# Q8

In [51]:
filtered = df.loc[(df['role'] == 'HR Executive') | (df['role'] == 'HR Manager')]

print(f"filtered employee count: {len(filtered)}")
filtered

filtered employee count: 9

    emp_id  emp_age  emp_salary          role
0      101       54       51725    HR Manager
5      106       37       58915    HR Manager
9      110       38       90494  HR Executive
24     125       53       60584  HR Executive
27     128       21       71888  HR Executive
38     139       27       52013    HR Manager
42     143       47       55523  HR Executive
44     145       22       90794  HR Executive
45     146       52       41061    HR Manager

# Q9

In [65]:
df.sort_values(by= ['emp_age', 'emp_salary'],ascending=[True, False], inplace=True)
df.reset_index(drop=True, inplace=True)

df.loc[0:4, ['emp_id', 'role', 'emp_salary']]

   emp_id                role  emp_salary
0     131     Sales Executive       82550
1     119  Software Developer       63187
2     142    Digital Marketer       59500
3     103  Operations Manager       35452
4     137     Sales Executive       94427

# Q10

In [72]:
increase_tech_role = emp_income.copy()

for i in range(len(emp_roles)):
  if emp_roles[i] == 'Software Developer' or emp_roles[i] == 'Backend Developer':
    increase_tech_role[i] = increase_tech_role[i] * 1.12
  else :
    increase_tech_role[i] = increase_tech_role[i] * 1.05

increase_salary = increase_tech_role - emp_income

data = {
    'role': emp_roles,
    'previous_salary': emp_income,
    'new_salary': increase_tech_role,
    'increase_of_salary': increase_salary
}
dataset = pd.DataFrame(data)

dataset

                   role  previous_salary  new_salary  increase_of_salary
0            HR Manager            51725       54311                2586
1            Accountant            38495       40419                1924
2    Operations Manager            35452       37224                1772
3      Digital Marketer            82295       86409                4114
4     Backend Developer            72187       80849                8662
5            HR Manager            58915       61860                2945
6     Backend Developer            76159       85298                9139
7       Sales Executive            92864       97507                4643
8       Sales Executive            76155       79962                3807
9          HR Executive            90494       95018                4524
10    Backend Developer            68641       76877                8236
11  Marketing Executive            48079       50482                2403
12      Sales Executive            56879       59722                2843
13   Operations Manager            83682       87866                4184
14     Digital Marketer            94722       99458                4736
15    Financial Analyst            91041       95593                4552
16      Sales Executive            48899       51343                2444
17   Operations Manager            68744       72181                3437
18   Software Developer            63187       70769                7582
19    Backend Developer            74146       83043                8897
20      Sales Executive            75641       79423                3782
21      Sales Executive            47678       50061                2383
22           Accountant            76760       80598                3838
23   Software Developer            78354       87756                9402
24         HR Executive            60584       63613                3029
25   Operations Manager            79898       83892                3994
26     Digital Marketer            59682       62666                2984
27         HR Executive            71888       75482                3594
28   Software Developer            51086       57216                6130
29           Accountant            73700       77385                3685
30      Sales Executive            82550       86677                4127
31  Marketing Executive            71447       75019                3572
32     Digital Marketer            76100       79905                3805
33    Backend Developer            72269       80941                8672
34   Software Developer            73314       82111                8797
35   Software Developer            87428       97919               10491
36      Sales Executive            94427       99148                4721
37           Accountant            84188       88397                4209
38           HR Manager            52013       54613                2600
39      Sales Executive            63326       66492                3166
40  Marketing Executive            44396       46615                2219
41     Digital Marketer            59500       62475                2975
42         HR Executive            55523       58299                2776
43           Accountant            58602       61532                2930
44         HR Executive            90794       95333                4539
45           HR Manager            41061       43114                2053
46   Software Developer            82331       92210                9879
47   Software Developer            73048       81813                8765
48     Digital Marketer            59727       62713                2986
49  Marketing Executive            50398       52917                2519