## Pandas

In [ ]:
# pandas mainly ekta tool, jeta data preprocess cleaning eda feature engineering er jonno use hoy

import pandas as pd

dataset = pd.read_csv('student_data.csv') #pandas dataframe

print(dataset)

# pandas build kora hoice dataframe and series niye

   StudentID          FullName  Data Structure Marks  Algorithm Marks  \
0     PH1001       Alif Rahman                  85.0             85.0
1     PH1002     Fatima Akhter                  92.0             92.0
2     PH1003     Imran Hossain                  88.0             88.0
3     PH1004  Jannatul Ferdous                  78.0             78.0
4     PH1005       Kamal Uddin                   NaN              NaN
5     PH1006       Laila Begum                  75.0             75.0
6     PH1007    Mahmudul Hasan                  80.0             80.0
7     PH1008       Nadia Islam                  81.0             81.0
8     PH1009        Omar Faruq                  72.0             72.0
9     PH1010      Priya Sharma                  89.0             89.0
10    PH1011      Rahim Sheikh                   NaN              NaN
11    PH1012   Sadia Chowdhury                  85.0             85.0
12    PH1013      Tanvir Ahmed                  75.0             75.0
13    PH1014        Urmi Akter                   NaN              NaN
14    PH1015      Wahiduzzaman                  86.0             86.0
15    PH1016      Ziaur Rahman                  94.0             94.0
16    PH1017       Afsana Mimi                  90.0             90.0
17    PH1018       Babul Ahmed                  88.0             88.0
18    PH1019      Faria Rahman                   NaN              NaN
19    PH1020        Nasir Khan                  86.0             86.0

    Python Marks CompletionStatus EnrollmentDate Instructor    Location
0           88.0        Completed     2024-01-15  Mr. Karim       Dhaka
1            NaN      In Progress     2024-01-20  Ms. Salma  Chattogram
2           85.0        Completed     2024-02-10  Mr. Karim       Dhaka
3           82.0        Completed     2024-02-12  Ms. Salma      Sylhet
4           95.0      In Progress     2024-03-05  Mr. Karim  Chattogram
5           78.0        Completed     2024-03-08  Ms. Salma    Rajshahi
6            NaN      In Progress     2024-04-01  Mr. Karim       Dhaka
7           85.0        Completed     2024-04-22  Ms. Salma  Chattogram
8           76.0        Completed     2024-05-16  Mr. David       Dhaka
9           88.0        Completed     2024-05-20  Ms. Salma      Sylhet
10          91.0      In Progress     2024-06-11  Mr. Karim      Khulna
11          87.0        Completed     2024-06-14  Ms. Salma  Chattogram
12          79.0        Completed     2024-07-02  Mr. David       Dhaka
13           NaN      Not Started     2024-07-09  Ms. Salma    Rajshahi
14          84.0        Completed     2024-08-18  Mr. Karim       Dhaka
15           NaN      In Progress     2024-08-21  Ms. Salma  Chattogram
16          93.0        Completed     2025-09-01  Mr. Karim       Dhaka
17          85.0        Completed     2025-09-05  Ms. Salma      Sylhet
18           NaN      Not Started     2025-09-15  Mr. David  Chattogram
19          89.0        Completed     2025-10-02  Ms. Salma       Dhaka

In [2]:
print(type(dataset))

<class 'pandas.core.frame.DataFrame'>

In [ ]:
st_id = dataset['StudentID']
full_name = dataset['FullName']

# eikhane amra ektai matro data nite pari jeitake series bole

for i in range(len(st_id)):
    print(st_id[i], full_name[i])

PH1001 Alif Rahman
PH1002 Fatima Akhter
PH1003 Imran Hossain
PH1004 Jannatul Ferdous
PH1005 Kamal Uddin
PH1006 Laila Begum
PH1007 Mahmudul Hasan
PH1008 Nadia Islam
PH1009 Omar Faruq
PH1010 Priya Sharma
PH1011 Rahim Sheikh
PH1012 Sadia Chowdhury
PH1013 Tanvir Ahmed
PH1014 Urmi Akter
PH1015 Wahiduzzaman
PH1016 Ziaur Rahman
PH1017 Afsana Mimi
PH1018 Babul Ahmed
PH1019 Faria Rahman
PH1020 Nasir Khan

## Different file loading

In [ ]:
# excel data loading
csv_data = pd.read_excel("/home/tanmoy/Desktop/Phitron/Practice/Module10_pandas/phitron_student_marks.xlsx")

print(csv_data)

   StudentID          FullName  Data Structure Marks  Algorithm Marks  \
0     PH1001       Alif Rahman                  85.0             85.0
1     PH1002     Fatima Akhter                  92.0             92.0
2     PH1003     Imran Hossain                  88.0             88.0
3     PH1004  Jannatul Ferdous                  78.0             78.0
4     PH1005       Kamal Uddin                   NaN              NaN
5     PH1006       Laila Begum                  75.0             75.0
6     PH1007    Mahmudul Hasan                  80.0             80.0
7     PH1008       Nadia Islam                  81.0             81.0
8     PH1009        Omar Faruq                  72.0             72.0
9     PH1010      Priya Sharma                  89.0             89.0
10    PH1011      Rahim Sheikh                   NaN              NaN
11    PH1012   Sadia Chowdhury                  85.0             85.0
12    PH1013      Tanvir Ahmed                  75.0             75.0
13    PH1014        Urmi Akter                   NaN              NaN
14    PH1015      Wahiduzzaman                  86.0             86.0
15    PH1016      Ziaur Rahman                  94.0             94.0
16    PH1017       Afsana Mimi                  90.0             90.0
17    PH1018       Babul Ahmed                  88.0             88.0
18    PH1019      Faria Rahman                   NaN              NaN
19    PH1020        Nasir Khan                  86.0             86.0

    Python Marks CompletionStatus EnrollmentDate Instructor    Location
0           88.0        Completed     2024-01-15  Mr. Karim       Dhaka
1            NaN      In Progress     2024-01-20  Ms. Salma  Chattogram
2           85.0        Completed     2024-02-10  Mr. Karim       Dhaka
3           82.0        Completed     2024-02-12  Ms. Salma      Sylhet
4           95.0      In Progress     2024-03-05  Mr. Karim  Chattogram
5           78.0        Completed     2024-03-08  Ms. Salma    Rajshahi
6            NaN      In Progress     2024-04-01  Mr. Karim       Dhaka
7           85.0        Completed     2024-04-22  Ms. Salma  Chattogram
8           76.0        Completed     2024-05-16  Mr. David       Dhaka
9           88.0        Completed     2024-05-20  Ms. Salma      Sylhet
10          91.0      In Progress     2024-06-11  Mr. Karim      Khulna
11          87.0        Completed     2024-06-14  Ms. Salma  Chattogram
12          79.0        Completed     2024-07-02  Mr. David       Dhaka
13           NaN      Not Started     2024-07-09  Ms. Salma    Rajshahi
14          84.0        Completed     2024-08-18  Mr. Karim       Dhaka
15           NaN      In Progress     2024-08-21  Ms. Salma  Chattogram
16          93.0        Completed     2025-09-01  Mr. Karim       Dhaka
17          85.0        Completed     2025-09-05  Ms. Salma      Sylhet
18           NaN      Not Started     2025-09-15  Mr. David  Chattogram
19          89.0        Completed     2025-10-02  Ms. Salma       Dhaka

In [13]:
# Json file loading 

json_data = pd.read_json("/home/tanmoy/Desktop/Phitron/Practice/Module10_pandas/data.json")

print(json_data)

  StudentID          FullName  Data Structure Marks  Algorithm Marks  \
0    PH1001       Alif Rahman                    85               85
1    PH1002     Fatima Akhter                    92               92
2    PH1004  Jannatul Ferdous                    78               78

   Python Marks
0            88
1            90
2            82

In [14]:
# read parquet file

perq_read = pd.read_parquet("/home/tanmoy/Desktop/Phitron/Practice/Module10_pandas/students.parquet")

print(perq_read)

   StudentID          FullName  Data Structure Marks  Algorithm Marks  \
0     PH1001       Alif Rahman                  85.0             85.0
1     PH1002     Fatima Akhter                  92.0             92.0
2     PH1003     Imran Hossain                  88.0             88.0
3     PH1004  Jannatul Ferdous                  78.0             78.0
4     PH1005       Kamal Uddin                   NaN              NaN
5     PH1006       Laila Begum                  75.0             75.0
6     PH1007    Mahmudul Hasan                  80.0             80.0
7     PH1008       Nadia Islam                  81.0             81.0
8     PH1009        Omar Faruq                  72.0             72.0
9     PH1010      Priya Sharma                  89.0             89.0
10    PH1011      Rahim Sheikh                   NaN              NaN
11    PH1012   Sadia Chowdhury                  85.0             85.0
12    PH1013      Tanvir Ahmed                  75.0             75.0
13    PH1014        Urmi Akter                   NaN              NaN
14    PH1015      Wahiduzzaman                  86.0             86.0
15    PH1016      Ziaur Rahman                  94.0             94.0
16    PH1017       Afsana Mimi                  90.0             90.0
17    PH1018       Babul Ahmed                  88.0             88.0
18    PH1019      Faria Rahman                   NaN              NaN
19    PH1020        Nasir Khan                  86.0             86.0

    Python Marks CompletionStatus EnrollmentDate Instructor    Location
0           88.0        Completed     2024-01-15  Mr. Karim       Dhaka
1            NaN      In Progress     2024-01-20  Ms. Salma  Chattogram
2           85.0        Completed     2024-02-10  Mr. Karim       Dhaka
3           82.0        Completed     2024-02-12  Ms. Salma      Sylhet
4           95.0      In Progress     2024-03-05  Mr. Karim  Chattogram
5           78.0        Completed     2024-03-08  Ms. Salma    Rajshahi
6            NaN      In Progress     2024-04-01  Mr. Karim       Dhaka
7           85.0        Completed     2024-04-22  Ms. Salma  Chattogram
8           76.0        Completed     2024-05-16  Mr. David       Dhaka
9           88.0        Completed     2024-05-20  Ms. Salma      Sylhet
10          91.0      In Progress     2024-06-11  Mr. Karim      Khulna
11          87.0        Completed     2024-06-14  Ms. Salma  Chattogram
12          79.0        Completed     2024-07-02  Mr. David       Dhaka
13           NaN      Not Started     2024-07-09  Ms. Salma    Rajshahi
14          84.0        Completed     2024-08-18  Mr. Karim       Dhaka
15           NaN      In Progress     2024-08-21  Ms. Salma  Chattogram
16          93.0        Completed     2025-09-01  Mr. Karim       Dhaka
17          85.0        Completed     2025-09-05  Ms. Salma      Sylhet
18           NaN      Not Started     2025-09-15  Mr. David  Chattogram
19          89.0        Completed     2025-10-02  Ms. Salma       Dhaka

In [15]:
dataset = pd.read_csv('student_data.csv') #pandas dataframe

dataset

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location
0,PH1001,Alif Rahman,85.0,85.0,88.0,Completed,2024-01-15,Mr. Karim,Dhaka
1,PH1002,Fatima Akhter,92.0,92.0,NaN,In Progress,2024-01-20,Ms. Salma,Chattogram
2,PH1003,Imran Hossain,88.0,88.0,85.0,Completed,2024-02-10,Mr. Karim,Dhaka
3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Ms. Salma,Sylhet
4,PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,2024-03-05,Mr. Karim,Chattogram
5,PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08,Ms. Salma,Rajshahi
6,PH1007,Mahmudul Hasan,80.0,80.0,NaN,In Progress,2024-04-01,Mr. Karim,Dhaka
7,PH1008,Nadia Islam,81.0,81.0,85.0,Completed,2024-04-22,Ms. Salma,Chattogram
8,PH1009,Omar Faruq,72.0,72.0,76.0,Completed,2024-05-16,Mr. David,Dhaka
9,PH1010,Priya Sharma,89.0,89.0,88.0,Completed,2024-05-20,Ms. Salma,Sylhet
10,PH1011,Rahim Sheikh,NaN,NaN,91.0,In Progress,2024-06-11,Mr. Karim,Khulna
11,PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,2024-06-14,Ms. Salma,Chattogram
12,PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,2024-07-02,Mr. David,Dhaka
13,PH1014,Urmi Akter,NaN,NaN,NaN,Not Started,2024-07-09,Ms. Salma,Rajshahi
14,PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,2024-08-18,Mr. Karim,Dhaka
15,PH1016,Ziaur Rahman,94.0,94.0,NaN,In Progress,2024-08-21,Ms. Salma,Chattogram
16,PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2025-09-01,Mr. Karim,Dhaka
17,PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,2025-09-05,Ms. Salma,Sylhet
18,PH1019,Faria Rahman,NaN,NaN,NaN,Not Started,2025-09-15,Mr. David,Chattogram
19,PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2025-10-02,Ms. Salma,Dhaka

In [18]:
dataset.head(5)

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location
0,PH1001,Alif Rahman,85.0,85.0,88.0,Completed,2024-01-15,Mr. Karim,Dhaka
1,PH1002,Fatima Akhter,92.0,92.0,NaN,In Progress,2024-01-20,Ms. Salma,Chattogram
2,PH1003,Imran Hossain,88.0,88.0,85.0,Completed,2024-02-10,Mr. Karim,Dhaka
3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Ms. Salma,Sylhet
4,PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,2024-03-05,Mr. Karim,Chattogram

In [20]:
dataset.tail(5)

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location
15,PH1016,Ziaur Rahman,94.0,94.0,NaN,In Progress,2024-08-21,Ms. Salma,Chattogram
16,PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2025-09-01,Mr. Karim,Dhaka
17,PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,2025-09-05,Ms. Salma,Sylhet
18,PH1019,Faria Rahman,NaN,NaN,NaN,Not Started,2025-09-15,Mr. David,Chattogram
19,PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2025-10-02,Ms. Salma,Dhaka

In [21]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 9 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   StudentID             20 non-null     object
 1   FullName              20 non-null     object
 2   Data Structure Marks  16 non-null     float64
 3   Algorithm Marks       16 non-null     float64
 4   Python Marks          15 non-null     float64
 5   CompletionStatus      20 non-null     object
 6   EnrollmentDate        20 non-null     object
 7   Instructor            20 non-null     object
 8   Location              20 non-null     object
dtypes: float64(3), object(6)
memory usage: 1.5+ KB

In [22]:
dataset.describe()

       Data Structure Marks  Algorithm Marks  Python Marks
count             16.000000        16.000000     15.000000
mean              84.000000        84.000000     85.666667
std                6.501282         6.501282      5.394000
min               72.000000        72.000000     76.000000
25%               79.500000        79.500000     83.000000
50%               85.500000        85.500000     85.000000
75%               88.250000        88.250000     88.500000
max               94.000000        94.000000     95.000000

In [ ]:
import numpy as np
dataset.columns

col = np.array(dataset.columns)
print(type(col))
print(col)

ind = np.array(dataset.index) # eita amader index guloke show kore
print()

print(ind)

<class 'numpy.ndarray'>
['StudentID' 'FullName' 'Data Structure Marks' 'Algorithm Marks'
 'Python Marks' 'CompletionStatus' 'EnrollmentDate' 'Instructor'
 'Location']

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]

In [ ]:
dataset.sample(10) # eita amader random sample show kore

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location
13,PH1014,Urmi Akter,NaN,NaN,NaN,Not Started,2024-07-09,Ms. Salma,Rajshahi
8,PH1009,Omar Faruq,72.0,72.0,76.0,Completed,2024-05-16,Mr. David,Dhaka
7,PH1008,Nadia Islam,81.0,81.0,85.0,Completed,2024-04-22,Ms. Salma,Chattogram
15,PH1016,Ziaur Rahman,94.0,94.0,NaN,In Progress,2024-08-21,Ms. Salma,Chattogram
17,PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,2025-09-05,Ms. Salma,Sylhet
6,PH1007,Mahmudul Hasan,80.0,80.0,NaN,In Progress,2024-04-01,Mr. Karim,Dhaka
18,PH1019,Faria Rahman,NaN,NaN,NaN,Not Started,2025-09-15,Mr. David,Chattogram
3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Ms. Salma,Sylhet
4,PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,2024-03-05,Mr. Karim,Chattogram
9,PH1010,Priya Sharma,89.0,89.0,88.0,Completed,2024-05-20,Ms. Salma,Sylhet

## List touple and dictonary to make a pandas dataframe

In [ ]:
lst = [['tan', 10], ['man', 20]]

ds = pd.DataFrame(lst, columns=['Name','Age']) # list theke pnadas dataframe

ds

  Name  Age
0  tan   10
1  man   20

In [ ]:
tpl = (('tan',10), ('man', 10))

ds = pd.DataFrame(tpl, columns=['Name', 'Age']) #touple to pandas dataframe conversion

ds

  Name  Age
0  tan   10
1  man   10

In [ ]:
dic = {
    'Name' : ['tan', 'man'],
    'Age' : [10,20]
}

ds = pd.DataFrame(dic) #dictionary to pandas dataframe

ds

  Name  Age
0  tan   10
1  man   20

In [ ]:
dic = [
    {'Name' : 'tan', 'Age' : 10, 'City' : 'Barishal'},
    {'Name' : 'man', 'Age' : 10, 'City' : 'Khulna'},
    {'Name' : 'tan', 'City' : 'Barishal'}
]

print(type(dic))

ds = pd.DataFrame(dic) #eikhane kintu null value show kortice 
# uporer way tea null value daoar kono option e chilo nah
ds

<class 'list'>

  Name   Age      City
0  tan  10.0  Barishal
1  man  10.0    Khulna
2  tan   NaN  Barishal

## loc and iloc use kore pandas accessing

In [42]:
dataset.loc[1]

StudentID                      PH1002
FullName                Fatima Akhter
Data Structure Marks             92.0
Algorithm Marks                  92.0
Python Marks                      NaN
CompletionStatus          In Progress
EnrollmentDate             2024-01-20
Instructor                  Ms. Salma
Location                   Chattogram
Name: 1, dtype: object

In [43]:
dataset[1:5]

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location
1,PH1002,Fatima Akhter,92.0,92.0,NaN,In Progress,2024-01-20,Ms. Salma,Chattogram
2,PH1003,Imran Hossain,88.0,88.0,85.0,Completed,2024-02-10,Mr. Karim,Dhaka
3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Ms. Salma,Sylhet
4,PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,2024-03-05,Mr. Karim,Chattogram

In [44]:
dataset.loc[:,'FullName']

0          Alif Rahman
1        Fatima Akhter
2        Imran Hossain
3     Jannatul Ferdous
4          Kamal Uddin
5          Laila Begum
6       Mahmudul Hasan
7          Nadia Islam
8           Omar Faruq
9         Priya Sharma
10        Rahim Sheikh
11     Sadia Chowdhury
12        Tanvir Ahmed
13          Urmi Akter
14        Wahiduzzaman
15        Ziaur Rahman
16         Afsana Mimi
17         Babul Ahmed
18        Faria Rahman
19          Nasir Khan
Name: FullName, dtype: object

In [49]:
dataset.loc[1:5, ['FullName', 'Python Marks']]

           FullName  Python Marks
1     Fatima Akhter           NaN
2     Imran Hossain          85.0
3  Jannatul Ferdous          82.0
4       Kamal Uddin          95.0
5       Laila Begum          78.0

## Uses of iloc

In [ ]:
df = dataset.set_index('StudentID')
df

df.iloc[0:9] # amar index kintu ekhon ar numerical value nei
# tao ami access korte cacchi numerical value diye, ei somoy mainly iloc use hoy

,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location
StudentID,,,,,,,,
PH1001,Alif Rahman,85.0,85.0,88.0,Completed,2024-01-15,Mr. Karim,Dhaka
PH1002,Fatima Akhter,92.0,92.0,NaN,In Progress,2024-01-20,Ms. Salma,Chattogram
PH1003,Imran Hossain,88.0,88.0,85.0,Completed,2024-02-10,Mr. Karim,Dhaka
PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Ms. Salma,Sylhet
PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,2024-03-05,Mr. Karim,Chattogram
PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08,Ms. Salma,Rajshahi
PH1007,Mahmudul Hasan,80.0,80.0,NaN,In Progress,2024-04-01,Mr. Karim,Dhaka
PH1008,Nadia Islam,81.0,81.0,85.0,Completed,2024-04-22,Ms. Salma,Chattogram
PH1009,Omar Faruq,72.0,72.0,76.0,Completed,2024-05-16,Mr. David,Dhaka

## Column rename

In [ ]:
df.rename(columns={'StudentID' : 'ID'}, inplace=True)
df

,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location
StudentID,,,,,,,,
PH1001,Alif Rahman,85.0,85.0,88.0,Completed,2024-01-15,Mr. Karim,Dhaka
PH1002,Fatima Akhter,92.0,92.0,NaN,In Progress,2024-01-20,Ms. Salma,Chattogram
PH1003,Imran Hossain,88.0,88.0,85.0,Completed,2024-02-10,Mr. Karim,Dhaka
PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Ms. Salma,Sylhet
PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,2024-03-05,Mr. Karim,Chattogram
PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08,Ms. Salma,Rajshahi
PH1007,Mahmudul Hasan,80.0,80.0,NaN,In Progress,2024-04-01,Mr. Karim,Dhaka
PH1008,Nadia Islam,81.0,81.0,85.0,Completed,2024-04-22,Ms. Salma,Chattogram
PH1009,Omar Faruq,72.0,72.0,76.0,Completed,2024-05-16,Mr. David,Dhaka
PH1010,Priya Sharma,89.0,89.0,88.0,Completed,2024-05-20,Ms. Salma,Sylhet
PH1011,Rahim Sheikh,NaN,NaN,91.0,In Progress,2024-06-11,Mr. Karim,Khulna
PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,2024-06-14,Ms. Salma,Chattogram
PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,2024-07-02,Mr. David,Dhaka
PH1014,Urmi Akter,NaN,NaN,NaN,Not Started,2024-07-09,Ms. Salma,Rajshahi
PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,2024-08-18,Mr. Karim,Dhaka
PH1016,Ziaur Rahman,94.0,94.0,NaN,In Progress,2024-08-21,Ms. Salma,Chattogram
PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2025-09-01,Mr. Karim,Dhaka
PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,2025-09-05,Ms. Salma,Sylhet
PH1019,Faria Rahman,NaN,NaN,NaN,Not Started,2025-09-15,Mr. David,Chattogram
PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2025-10-02,Ms. Salma,Dhaka

## delete using pandas

In [ ]:
dataset
dataset.drop(0, inplace=True) #row delete

In [70]:
dataset

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location
1,PH1002,Fatima Akhter,92.0,92.0,NaN,In Progress,2024-01-20,Ms. Salma,Chattogram
2,PH1003,Imran Hossain,88.0,88.0,85.0,Completed,2024-02-10,Mr. Karim,Dhaka
3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Ms. Salma,Sylhet
4,PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,2024-03-05,Mr. Karim,Chattogram
5,PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08,Ms. Salma,Rajshahi
6,PH1007,Mahmudul Hasan,80.0,80.0,NaN,In Progress,2024-04-01,Mr. Karim,Dhaka
7,PH1008,Nadia Islam,81.0,81.0,85.0,Completed,2024-04-22,Ms. Salma,Chattogram
8,PH1009,Omar Faruq,72.0,72.0,76.0,Completed,2024-05-16,Mr. David,Dhaka
9,PH1010,Priya Sharma,89.0,89.0,88.0,Completed,2024-05-20,Ms. Salma,Sylhet
10,PH1011,Rahim Sheikh,NaN,NaN,91.0,In Progress,2024-06-11,Mr. Karim,Khulna
11,PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,2024-06-14,Ms. Salma,Chattogram
12,PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,2024-07-02,Mr. David,Dhaka
13,PH1014,Urmi Akter,NaN,NaN,NaN,Not Started,2024-07-09,Ms. Salma,Rajshahi
14,PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,2024-08-18,Mr. Karim,Dhaka
15,PH1016,Ziaur Rahman,94.0,94.0,NaN,In Progress,2024-08-21,Ms. Salma,Chattogram
16,PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2025-09-01,Mr. Karim,Dhaka
17,PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,2025-09-05,Ms. Salma,Sylhet
18,PH1019,Faria Rahman,NaN,NaN,NaN,Not Started,2025-09-15,Mr. David,Chattogram
19,PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2025-10-02,Ms. Salma,Dhaka

In [ ]:
dataset.drop(columns='Instructor', axis=1, inplace=True) # eita column drop mane column delete kora ekta

In [72]:
dataset

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Location
1,PH1002,Fatima Akhter,92.0,92.0,NaN,In Progress,2024-01-20,Chattogram
2,PH1003,Imran Hossain,88.0,88.0,85.0,Completed,2024-02-10,Dhaka
3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Sylhet
4,PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,2024-03-05,Chattogram
5,PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08,Rajshahi
6,PH1007,Mahmudul Hasan,80.0,80.0,NaN,In Progress,2024-04-01,Dhaka
7,PH1008,Nadia Islam,81.0,81.0,85.0,Completed,2024-04-22,Chattogram
8,PH1009,Omar Faruq,72.0,72.0,76.0,Completed,2024-05-16,Dhaka
9,PH1010,Priya Sharma,89.0,89.0,88.0,Completed,2024-05-20,Sylhet
10,PH1011,Rahim Sheikh,NaN,NaN,91.0,In Progress,2024-06-11,Khulna
11,PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,2024-06-14,Chattogram
12,PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,2024-07-02,Dhaka
13,PH1014,Urmi Akter,NaN,NaN,NaN,Not Started,2024-07-09,Rajshahi
14,PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,2024-08-18,Dhaka
15,PH1016,Ziaur Rahman,94.0,94.0,NaN,In Progress,2024-08-21,Chattogram
16,PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2025-09-01,Dhaka
17,PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,2025-09-05,Sylhet
18,PH1019,Faria Rahman,NaN,NaN,NaN,Not Started,2025-09-15,Chattogram
19,PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2025-10-02,Dhaka

In [ ]:
dataset.loc[1, 'Python Marks'] = 90 # single elemet access and update

In [74]:
dataset

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Location
1,PH1002,Fatima Akhter,92.0,92.0,90.0,In Progress,2024-01-20,Chattogram
2,PH1003,Imran Hossain,88.0,88.0,85.0,Completed,2024-02-10,Dhaka
3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Sylhet
4,PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,2024-03-05,Chattogram
5,PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08,Rajshahi
6,PH1007,Mahmudul Hasan,80.0,80.0,NaN,In Progress,2024-04-01,Dhaka
7,PH1008,Nadia Islam,81.0,81.0,85.0,Completed,2024-04-22,Chattogram
8,PH1009,Omar Faruq,72.0,72.0,76.0,Completed,2024-05-16,Dhaka
9,PH1010,Priya Sharma,89.0,89.0,88.0,Completed,2024-05-20,Sylhet
10,PH1011,Rahim Sheikh,NaN,NaN,91.0,In Progress,2024-06-11,Khulna
11,PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,2024-06-14,Chattogram
12,PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,2024-07-02,Dhaka
13,PH1014,Urmi Akter,NaN,NaN,NaN,Not Started,2024-07-09,Rajshahi
14,PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,2024-08-18,Dhaka
15,PH1016,Ziaur Rahman,94.0,94.0,NaN,In Progress,2024-08-21,Chattogram
16,PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2025-09-01,Dhaka
17,PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,2025-09-05,Sylhet
18,PH1019,Faria Rahman,NaN,NaN,NaN,Not Started,2025-09-15,Chattogram
19,PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2025-10-02,Dhaka

In [ ]:
dataset.loc[1:3, 'Python Marks'] += 2 # multiple data access and update

In [76]:
dataset

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Location
1,PH1002,Fatima Akhter,92.0,92.0,92.0,In Progress,2024-01-20,Chattogram
2,PH1003,Imran Hossain,88.0,88.0,87.0,Completed,2024-02-10,Dhaka
3,PH1004,Jannatul Ferdous,78.0,78.0,84.0,Completed,2024-02-12,Sylhet
4,PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,2024-03-05,Chattogram
5,PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08,Rajshahi
6,PH1007,Mahmudul Hasan,80.0,80.0,NaN,In Progress,2024-04-01,Dhaka
7,PH1008,Nadia Islam,81.0,81.0,85.0,Completed,2024-04-22,Chattogram
8,PH1009,Omar Faruq,72.0,72.0,76.0,Completed,2024-05-16,Dhaka
9,PH1010,Priya Sharma,89.0,89.0,88.0,Completed,2024-05-20,Sylhet
10,PH1011,Rahim Sheikh,NaN,NaN,91.0,In Progress,2024-06-11,Khulna
11,PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,2024-06-14,Chattogram
12,PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,2024-07-02,Dhaka
13,PH1014,Urmi Akter,NaN,NaN,NaN,Not Started,2024-07-09,Rajshahi
14,PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,2024-08-18,Dhaka
15,PH1016,Ziaur Rahman,94.0,94.0,NaN,In Progress,2024-08-21,Chattogram
16,PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2025-09-01,Dhaka
17,PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,2025-09-05,Sylhet
18,PH1019,Faria Rahman,NaN,NaN,NaN,Not Started,2025-09-15,Chattogram
19,PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2025-10-02,Dhaka

## Pandas sort

In [78]:
dataset

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Location
1,PH1002,Fatima Akhter,92.0,92.0,92.0,In Progress,2024-01-20,Chattogram
2,PH1003,Imran Hossain,88.0,88.0,87.0,Completed,2024-02-10,Dhaka
3,PH1004,Jannatul Ferdous,78.0,78.0,84.0,Completed,2024-02-12,Sylhet
4,PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,2024-03-05,Chattogram
5,PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08,Rajshahi
6,PH1007,Mahmudul Hasan,80.0,80.0,NaN,In Progress,2024-04-01,Dhaka
7,PH1008,Nadia Islam,81.0,81.0,85.0,Completed,2024-04-22,Chattogram
8,PH1009,Omar Faruq,72.0,72.0,76.0,Completed,2024-05-16,Dhaka
9,PH1010,Priya Sharma,89.0,89.0,88.0,Completed,2024-05-20,Sylhet
10,PH1011,Rahim Sheikh,NaN,NaN,91.0,In Progress,2024-06-11,Khulna
11,PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,2024-06-14,Chattogram
12,PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,2024-07-02,Dhaka
13,PH1014,Urmi Akter,NaN,NaN,NaN,Not Started,2024-07-09,Rajshahi
14,PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,2024-08-18,Dhaka
15,PH1016,Ziaur Rahman,94.0,94.0,NaN,In Progress,2024-08-21,Chattogram
16,PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2025-09-01,Dhaka
17,PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,2025-09-05,Sylhet
18,PH1019,Faria Rahman,NaN,NaN,NaN,Not Started,2025-09-15,Chattogram
19,PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2025-10-02,Dhaka

In [80]:
dataset.sort_values('Data Structure Marks')

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Location
8,PH1009,Omar Faruq,72.0,72.0,76.0,Completed,2024-05-16,Dhaka
5,PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08,Rajshahi
12,PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,2024-07-02,Dhaka
3,PH1004,Jannatul Ferdous,78.0,78.0,84.0,Completed,2024-02-12,Sylhet
6,PH1007,Mahmudul Hasan,80.0,80.0,NaN,In Progress,2024-04-01,Dhaka
7,PH1008,Nadia Islam,81.0,81.0,85.0,Completed,2024-04-22,Chattogram
11,PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,2024-06-14,Chattogram
14,PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,2024-08-18,Dhaka
19,PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2025-10-02,Dhaka
17,PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,2025-09-05,Sylhet
2,PH1003,Imran Hossain,88.0,88.0,87.0,Completed,2024-02-10,Dhaka
9,PH1010,Priya Sharma,89.0,89.0,88.0,Completed,2024-05-20,Sylhet
16,PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2025-09-01,Dhaka
1,PH1002,Fatima Akhter,92.0,92.0,92.0,In Progress,2024-01-20,Chattogram
15,PH1016,Ziaur Rahman,94.0,94.0,NaN,In Progress,2024-08-21,Chattogram
4,PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,2024-03-05,Chattogram
10,PH1011,Rahim Sheikh,NaN,NaN,91.0,In Progress,2024-06-11,Khulna
13,PH1014,Urmi Akter,NaN,NaN,NaN,Not Started,2024-07-09,Rajshahi
18,PH1019,Faria Rahman,NaN,NaN,NaN,Not Started,2025-09-15,Chattogram

In [83]:
dataset.sort_values('Data Structure Marks', ascending=False)

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Location
15,PH1016,Ziaur Rahman,94.0,94.0,NaN,In Progress,2024-08-21,Chattogram
1,PH1002,Fatima Akhter,92.0,92.0,92.0,In Progress,2024-01-20,Chattogram
16,PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2025-09-01,Dhaka
9,PH1010,Priya Sharma,89.0,89.0,88.0,Completed,2024-05-20,Sylhet
17,PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,2025-09-05,Sylhet
2,PH1003,Imran Hossain,88.0,88.0,87.0,Completed,2024-02-10,Dhaka
14,PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,2024-08-18,Dhaka
19,PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2025-10-02,Dhaka
11,PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,2024-06-14,Chattogram
7,PH1008,Nadia Islam,81.0,81.0,85.0,Completed,2024-04-22,Chattogram
6,PH1007,Mahmudul Hasan,80.0,80.0,NaN,In Progress,2024-04-01,Dhaka
3,PH1004,Jannatul Ferdous,78.0,78.0,84.0,Completed,2024-02-12,Sylhet
5,PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08,Rajshahi
12,PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,2024-07-02,Dhaka
8,PH1009,Omar Faruq,72.0,72.0,76.0,Completed,2024-05-16,Dhaka
4,PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,2024-03-05,Chattogram
10,PH1011,Rahim Sheikh,NaN,NaN,91.0,In Progress,2024-06-11,Khulna
13,PH1014,Urmi Akter,NaN,NaN,NaN,Not Started,2024-07-09,Rajshahi
18,PH1019,Faria Rahman,NaN,NaN,NaN,Not Started,2025-09-15,Chattogram

In [84]:
dataset.sort_values('Data Structure Marks','Python Marks', ascending=False)

TypeError: DataFrame.sort_values() takes 2 positional arguments but 3 positional arguments (and 1 keyword-only argument) were given