In [5]:
import pandas as pd

data = {
    "Name": ["Alice", "Bob", "Charlie", "David", "Eve", "Frank", "Grace", "Hannah","Sakib"],
    "City": ["New York", "Los Angeles", "Newark", "Boston", "New Delhi", "Chicago", "New Orleans", "Houston","H Los Ang"],
    "Department": ["HR", "IT", "Finance", "IT", "HR", "Marketing", "Finance", "HR", "HR"],
    "Salary": [50000, 60000, 55000, 70000, 52000, 58000, 62000, 51000,70000]
}

df = pd.DataFrame(data)

In [11]:
df

      Name         City Department  Salary
0    Alice     New York         HR   50000
1      Bob  Los Angeles         IT   60000
2  Charlie       Newark    Finance   55000
3    David       Boston         IT   70000
4      Eve    New Delhi         HR   52000
5    Frank      Chicago  Marketing   58000
6    Grace  New Orleans    Finance   62000
7   Hannah      Houston         HR   51000
8    Sakib    H Los Ang         HR   70000

### Handling duplicates

In [7]:
df["Department"].duplicated()

0    False
1    False
2    False
3     True
4     True
5    False
6     True
7     True
8     True
Name: Department, dtype: bool

In [ ]:
df["Department"].duplicated().sum() # koyta duplicate ache dekhay

np.int64(5)

In [ ]:
df.drop_duplicates() # eita mainly index based duplicate remove kore

      Name         City Department  Salary
0    Alice     New York         HR   50000
1      Bob  Los Angeles         IT   60000
2  Charlie       Newark    Finance   55000
3    David       Boston         IT   70000
4      Eve    New Delhi         HR   52000
5    Frank      Chicago  Marketing   58000
6    Grace  New Orleans    Finance   62000
7   Hannah      Houston         HR   51000
8    Sakib    H Los Ang         HR   70000

In [15]:
df.drop_duplicates(subset="Department") 
# ekta column ba multiple column er er theke remove kore

      Name         City Department  Salary
0    Alice     New York         HR   50000
1      Bob  Los Angeles         IT   60000
2  Charlie       Newark    Finance   55000
5    Frank      Chicago  Marketing   58000

In [16]:
df.drop_duplicates(subset="Department", keep="first") 
# first er index take rakhe

      Name         City Department  Salary
0    Alice     New York         HR   50000
1      Bob  Los Angeles         IT   60000
2  Charlie       Newark    Finance   55000
5    Frank      Chicago  Marketing   58000

In [17]:
df.drop_duplicates(subset="Department", keep="last") 
# last er index take rakhe

    Name         City Department  Salary
3  David       Boston         IT   70000
5  Frank      Chicago  Marketing   58000
6  Grace  New Orleans    Finance   62000
8  Sakib    H Los Ang         HR   70000

In [ ]:
df # that didnt change caude it creates a copy

      Name         City Department  Salary
0    Alice     New York         HR   50000
1      Bob  Los Angeles         IT   60000
2  Charlie       Newark    Finance   55000
3    David       Boston         IT   70000
4      Eve    New Delhi         HR   52000
5    Frank      Chicago  Marketing   58000
6    Grace  New Orleans    Finance   62000
7   Hannah      Houston         HR   51000
8    Sakib    H Los Ang         HR   70000

In [19]:
df.drop_duplicates(subset="Department", keep="last", inplace=True)

In [ ]:
df # inplace true korar karone eta permanent change hoice

    Name         City Department  Salary
3  David       Boston         IT   70000
5  Frank      Chicago  Marketing   58000
6  Grace  New Orleans    Finance   62000
8  Sakib    H Los Ang         HR   70000